-- start transaction
BEGIN;

------------------- business logic -------------------

CREATE TABLE IF NOT EXISTS orchestrator.migration_dag_dependency (
    id SERIAL PRIMARY KEY,
    file_type VARCHAR(50) NOT NULL,
    depends_on VARCHAR(50) NOT NULL,
    label VARCHAR(200),
     max_executions INT,
    CONSTRAINT dag_dep_unique UNIQUE (file_type, depends_on)
);


INSERT INTO orchestrator.migration_dag_dependency(id,file_type,depends_on,label, max_executions) VALUES
(1 ,'ROOT','ROOT','ROOT',0),
(2 ,'ORGANIZATIONS','ROOT','ORGANIZATIONS',1),
(3 ,'ORG_SIL_SERVICES','ORGANIZATIONS',NULL,1),
(4 ,'DEBT_POSITIONS_TYPE','ROOT','DEBT_POSITIONS_TYPE',1),
(5 ,'DEBT_POSITIONS_TYPE_ORG','ORGANIZATIONS','DEBT_POSITIONS_TYPE_ORG',1),
(6 ,'DEBT_POSITIONS_TYPE_ORG_OPERATORS','DEBT_POSITIONS_TYPE_ORG','DEBT_POSITIONS_TYPE_ORG_OPERATORS',1),
(7 ,'DEBT_POSITIONS','DEBT_POSITIONS_TYPE_ORG','DEBT_POSITIONS',null),
(8 ,'DEBT_POSITIONS_PAID','DEBT_POSITIONS_TYPE_ORG','DEBT_POSITIONS_PAID',null),
(9 ,'PAYMENT_NOTIFICATION','DEBT_POSITIONS_TYPE_ORG','PAYMENT_NOTIFICATION',null),
(10,'PAYMENTS_REPORTING','DEBT_POSITIONS_TYPE_ORG','PAYMENTS_REPORTING',null),
(11,'TREASURY_CSV_COMPLETE','DEBT_POSITIONS_TYPE_ORG','TREASURY_CSV_COMPLETE',null),
(12,'ASSESSMENTS_REGISTRY','DEBT_POSITIONS_TYPE_ORG','ASSESSMENTS_REGISTRY',null),
(13,'ASSESSMENTS','DEBT_POSITIONS_PAID','ASSESSMENTS',null);

-- final commit
COMMIT;